#! /usr/bin/make

include Makefile.common

LIB += -L/opt/local/lib -framework Foundation -framework Carbon -framework AppKit -framework OpenGL

small: $(EXEC)
	strip $(EXEC)
# TODO: OSX smallifications here!

$(EXEC): opengl.o
	$(CC) -Oz -I/opt/local/include opengl.c -o $(EXEC) $(LDFLAGS) $(LIB)
