#! /usr/bin/make

include Makefile.common

LDFLAGS += -L/opt/local/lib -lSDLmain -lSDL -lGLEW -framework Foundation -framework Carbon -framework AppKit -framework OpenGL

small: $(EXEC)
	strip $(EXEC)
# TODO: OSX smallifications here!

$(EXEC): opengl.o
	$(CC) -Oz -I/opt/local/include opengl.c -o $(EXEC) $(LDFLAGS)
